osx_image: xcode10.1
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild build -workspace Example/UIDeviceIcon_Example.xcworkspace -scheme UIDeviceIcon -sdk iphonesimulator12.1 -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.1' | xcpretty
- pod lib lint
